micronaut:
  application:
    name: jwks
  server:
    port: 41518

jwt:
  token:
    expiry-minutes: ${TOKEN_EXPIRY_MINUTES:13}

jwk:
  storage:
    directory: /var/lib/jwks
    enabled: true
  rotation:
    enabled: true
    interval-minutes: ${JWK_ROTATION_INTERVAL_MINUTES:1440}
    initial-delay-minutes: 60

endpoints:
  health:
    enabled: true
    sensitive: false

logging:
  level:
    com.doruk.jwks: INFO
